import type { Property, SiteSettings } from "./types";
import heroVillaImage from "../assets/hero-villa.png";
import islandVillaImage from "../assets/island-villa.png";
import penthouseImage from "../assets/penthouse.png";

export const defaultProperties: Property[] = [
  {
    slug: "villa-solenne",
    name: "Villa Solenne",
    location: "French Riviera",
    destination: "riviera",
    image: heroVillaImage,
    images: [heroVillaImage],
    priceUsd: 18500000,
    priceLabel: "POA",
    tags: ["Beachfront", "Wellness", "Investment"],
    privacy: "A+",
    specs: "7 beds / 1,180 sqm / yacht approach",
    bedrooms: 7,
    interior: "1,180 sqm",
    security: "A+",
    payment: "BTC / ETH",
    yield: "7.8%",
    occupancy: "71%",
    coordinates: { left: "28%", top: "28%" },
    metrics: ["Southwest view", "Staff quarters", "A+ security", "BTC / ETH"],
    explanation:
      "AURA VILLA prepares a private illustrated brief for Villa Solenne, translating the rented unit into readable room drawings, arrival diagrams, amenity maps, and guest-ready spatial notes before the stay begins.",
    illustrationSet: [
      "Arrival sequence with guarded entry and yacht approach",
      "Room-by-room usage drawings for family, staff, and guests",
      "Wellness suite and beach access orientation",
      "Sunset salon, pool, and entertainment flow sketches",
    ],
    neighborhood: ["Private beach access", "Yacht approach", "Michelin dining corridor", "Nice private aviation"],
    rooms: ["Grand Salon", "Owner Suite", "Spa", "Cinema", "Staff Wing"],
  },
  {
    slug: "obsidian-penthouse",
    name: "The Obsidian Penthouse",
    location: "Dubai Skyline",
    destination: "dubai",
    image: penthouseImage,
    images: [penthouseImage],
    priceUsd: 11200000,
    priceLabel: "$11.2M",
    tags: ["Penthouse", "Investment"],
    privacy: "A",
    specs: "5 beds / private lift / skyline terrace",
    bedrooms: 5,
    interior: "760 sqm",
    security: "A",
    payment: "AED / USD",
    yield: "8.9%",
    occupancy: "79%",
    coordinates: { left: "62%", top: "48%" },
    metrics: ["West view", "Private lift", "A security", "AED / USD"],
    explanation:
      "AURA VILLA turns The Obsidian Penthouse into a clear visual operating guide with terrace diagrams, private-lift arrival drawings, hosting zones, and view-orientation notes for executive guests.",
    illustrationSet: [
      "Private lift arrival and lobby privacy diagram",
      "Terrace, skyline view, and evening hosting map",
      "Suite allocation drawings for VIP short stays",
      "Managed rental readiness and service path sketch",
    ],
    neighborhood: ["Private lift lobby", "Designer retail", "Financial district access", "Premium dining"],
    rooms: ["Sky Salon", "Terrace", "Owner Suite", "Wine Room", "Media Lounge"],
  },
  {
    slug: "nura-island-estate",
    name: "Nura Island Estate",
    location: "Maldives Private Atoll",
    destination: "maldives",
    image: islandVillaImage,
    images: [islandVillaImage],
    priceUsd: 26500000,
    priceLabel: "POA",
    tags: ["Private Island", "Beachfront", "Wellness"],
    privacy: "A+",
    specs: "8 beds / yacht dock / wellness pavilion",
    bedrooms: 8,
    interior: "1,420 sqm",
    security: "A+",
    payment: "BTC / ETH",
    yield: "9.4%",
    occupancy: "82%",
    coordinates: { left: "44%", top: "72%" },
    metrics: ["360 water view", "Full staff wing", "A+ security", "BTC / ETH"],
    explanation:
      "AURA VILLA creates an illustrated island brief for Nura Island Estate, showing yacht arrival, staff circulation, wellness pavilion access, and the full guest experience in precise visual form.",
    illustrationSet: [
      "Yacht dock, lagoon arrival, and seaplane transfer plan",
      "Staff wing circulation separated from guest zones",
      "Wellness pavilion and spa journey drawings",
      "360 water-view orientation and privacy map",
    ],
    neighborhood: ["Private yacht dock", "Lagoon arrival", "Wellness pavilion", "Seaplane transfer"],
    rooms: ["Salon", "Spa", "Cinema", "Owner Suite", "Staff Wing"],
  },
  {
    slug: "qamar-desert-reserve",
    name: "Qamar Desert Reserve",
    location: "Private Desert Enclave",
    destination: "desert",
    image: "assets/desert-villa.png",
    images: ["assets/desert-villa.png"],
    priceUsd: 9400000,
    priceLabel: "$9.4M",
    tags: ["Wellness", "Investment"],
    privacy: "A+",
    specs: "6 beds / courtyard pool / fire salon",
    bedrooms: 6,
    interior: "910 sqm",
    security: "A+",
    payment: "USD / AED",
    yield: "8.1%",
    occupancy: "68%",
    coordinates: { left: "72%", top: "26%" },
    metrics: ["Dune view", "Spa suite", "A+ security", "USD / AED"],
    explanation:
      "AURA VILLA documents Qamar Desert Reserve through illustrative drawings that clarify courtyard living, guarded access, spa movement, and private retreat zones for effortless arrival.",
    illustrationSet: [
      "Guarded reserve entry and arrival court diagram",
      "Courtyard pool, fire salon, and dining flow sketches",
      "Spa suite and wellness trail orientation",
      "Dune-view privacy and perimeter drawing",
    ],
    neighborhood: ["Private reserve", "Wellness trails", "Helipad request", "Desert dining"],
    rooms: ["Courtyard", "Pool Salon", "Spa Suite", "Owner Suite", "Fire Lounge"],
  },
];

export const defaultSiteSettings: SiteSettings = {
  brandName: "AURA VILLA",
  whatsappUrl: "https://wa.me/0000000000",
  defaultCurrency: "USD",
  cryptoPayments: "BTC / ETH indicators enabled",
  pendingRequests: 12,
};

export const rates = {
  USD: { symbol: "$", rate: 1 },
  EUR: { symbol: "EUR ", rate: 0.92 },
  AED: { symbol: "AED ", rate: 3.67 },
  GBP: { symbol: "GBP ", rate: 0.78 },
};
